part of station_app;

final ValueNotifier<String> langNotifier = ValueNotifier('ar');

class L {
  static String get(String key) {
    final lang = langNotifier.value;
    if (lang == 'en') return _en[key] ?? key;
    return _ar[key] ?? key;
  }

  static const Map<String, String> _ar = {
    // ── تنقل ──────────────────────────────
    'dashboard':        'الرئيسية',
    'gates':            'البوابات',
    'lines':            'الخطوط',
    'users':            'المستخدمون',
    'vehicles':         'المركبات',
    'violations':       'شكاوى',
    'reports':          'التقارير',
    'settings':         'الإعدادات',
    'requests':         'الطلبات',
    'notifications':    'الإشعارات',
    'profile':          'الملف الشخصي',
    'logout':           'تسجيل الخروج',
    // ── أزرار عامة ────────────────────────
    'add':              'إضافة',
    'edit':             'تعديل',
    'delete':           'حذف',
    'save':             'حفظ',
    'cancel':           'إلغاء',
    'search':           'بحث',
    'confirm':          'تأكيد',
    'close':            'إغلاق',
    'yes':              'نعم',
    'no':               'لا',
    'back':             'رجوع',
    'next':             'التالي',
    'filter':           'تصفية',
    'all':              'الكل',
    'loading':          'جاري التحميل...',
    'no_data':          'لا توجد بيانات',
    'coming_soon':      'قريباً...',
    'choose':           'اختر',
    'choose_role':      'اختر الدور',
    'choose_line':      'اختر الخط',
    'choose_gate':      'اختر البوابة',
    'choose_driver':    'اختر السائق',
    'name':             'الاسم',
    'date':             'التاريخ',
    'note':             'ملاحظة',
    'notes':            'ملاحظات',
    'amount':           'المبلغ',
    'status':           'الحالة',
    'actions':          'الإجراءات',
    'details':          'التفاصيل',
    'info':             'معلومات',
    'required':         'مطلوب',
    'optional':         'اختياري',
    'active':           'نشط',
    'inactive':         'غير نشط',
    'suspended':        'معلق',
    'unknown':          'غير معروف',
    'preview':          'معاينة',
    'print':            'طباعة',
    'export':           'تصدير',
    'share':            'مشاركة',
    'copy':             'نسخ',
    'copied':           'تم النسخ',
    'error':            'خطأ',
    'success':          'تم بنجاح',
    'warning':          'تحذير',
    // ── لوحة التحكم ───────────────────────
    'greeting_morning': 'صباح الخير',
    'greeting_afternoon':'مساء الخير',
    'greeting_evening': 'مساء النور',
    'station_name':     'محطة الحافلات المركزية — الخليل',
    'vehicle':          'مركبة',
    'line':             'خط',
    'user':             'مستخدم',
    'complaint':        'شكوى',
    'in_line':          'في الخط',
    'banned':           'محظورة',
    'ready':            'جاهزة',
    'waiting':          'انتظار',
    'vehicle_status':   'حالات المركبات',
    'event_stats':      'إحصائيات الأحداث',
    'no_vehicles':      'لا توجد مركبات بعد',
    'no_events':        'لا توجد أحداث بعد',
    'entry':            'دخول',
    'exit':             'خروج',
    'violation':        'مخالفة',
    // ── المستخدمون ────────────────────────
    'add_user':         'إضافة مستخدم',
    'edit_user':        'تعديل مستخدم',
    'user_info':        'معلومات المستخدم',
    'full_name':        'الاسم الكامل',
    'username':         'اسم المستخدم',
    'password':         'كلمة المرور',
    'role':             'الدور',
    'id_number':        'رقم الهوية',
    'phone':            'رقم الهاتف',
    'phone_optional':   'رقم الهاتف 2 (اختياري)',
    'phone_required':   'رقم الهاتف (إجباري)',
    'license_num':      'رقم الرخصة',
    'license_grade':    'درجة الرخصة',
    'license_expiry':   'انتهاء رخصة السائق',
    'medical_expiry':   'انتهاء الفحص الطبي',
    'mac_address':      'MAC Address',
    'account_active':   'الحساب مفعّل',
    'save_user':        'حفظ المستخدم',
    'driver':           'سائق',
    'security':         'موظف أمن',
    'supervisor':       'مشرف خط',
    'license_data':     'بيانات الرخصة والفحص الطبي',
    'user_saved':       'تم حفظ المستخدم بنجاح ✓',
    'enter_name':       'ادخل الاسم كاملاً',
    'enter_username':   'أدخل اسم المستخدم',
    'enter_password':   'أدخل كلمة المرور',
    'enter_id':         'رقم الهوية (9 أرقام)',
    'enter_phone':      '05xxxxxxxx',
    'enter_license':    'ادخل رقم الرخصة',
    'enter_grade':      'مثال: B, C, D',
    'enter_mac':        'مثال: AA:BB:CC:DD:EE:FF',
    'date_format':      'YYYY-MM-DD',
    'license_issue':    'تاريخ إصدار الرخصة',
    // ── المركبات ──────────────────────────
    'add_vehicle':      'إضافة مركبة',
    'edit_vehicle':     'تعديل مركبة',
    'vehicle_info':     'معلومات المركبة',
    'plate_number':     'رقم اللوحة',
    'manufacturer':     'الشركة المصنعة',
    'model':            'الطراز',
    'year':             'سنة الإنتاج',
    'chassis':          'رقم الشاصي',
    'op_lic_num':       'رقم رخصة التشغيل',
    'op_lic_exp':       'انتهاء رخصة التشغيل',
    'lic_exp':          'انتهاء الترخيص',
    'insurance_exp':    'انتهاء التأمين',
    'loading_exp':      'انتهاء التحميل',
    'owner_name':       'اسم المالك',
    'owner_phone':      'هاتف المالك',
    'owner_id':         'هوية المالك',
    'status_banned':    'محظورة',
    'status_waiting':   'في الانتظار',
    'status_ready':     'جاهزة',
    'status_in_line':   'في الخط',
    'vehicle_saved':    'تم حفظ المركبة بنجاح ✓',
    'rfid_tag':         'رقم RFID',
    'enter_plate':      'ادخل رقم اللوحة',
    'enter_chassis':    'ادخل رقم الشاصي',
    'enter_maker':      'مثال: Toyota',
    'enter_model':      'مثال: Hiace',
    'enter_year':       'مثال: 2020',
    'enter_rfid':       'ادخل رقم RFID',
    'enter_owner':      'ادخل اسم المالك',
    'enter_owner_phone':'ادخل هاتف المالك',
    'enter_owner_id':   'ادخل هوية المالك',
    'operating_license':'رخصة التشغيل',
    'enter_op_lic':     'مثال: OP-2024-556',
    'owner_info':       'معلومات المالك',
    'driver_and_line':  'السائق والخط',
    'driver_required':  'يجب اختيار السائق',
    'save_changes':     'حفظ التعديلات',
    // ── الخطوط ────────────────────────────
    'add_line':         'إضافة خط',
    'edit_line':        'تعديل خط',
    'line_info':        'معلومات الخط',
    'line_name':        'اسم الخط',
    'line_route':       'المسار',
    'entry_gate':       'بوابة الدخول',
    'exit_gate':        'بوابة الخروج',
    'fare':             'الأجرة',
    'loading_slots':    'مواقف التحميل',
    'no_lines':         'لا توجد خطوط بعد',
    'no_supervisor':    'بدون مشرف',
    'no_driver':        'بدون سائق',
    // ── الشكاوى ───────────────────────────
    'add_violation':    'إضافة شكوى',
    'edit_violation':   'تعديل شكوى',
    'violation_type':   'نوع الشكوى',
    'violation_amount': 'مبلغ الغرامة',
    'fees_paid':        'تم دفع الغرامة',
    'fees_unpaid':      'لم تُدفع الغرامة',
    'no_violations':    'لا توجد شكاوى بعد',
    'complaint_number':      'رقم الشكوى',
    'complaint_type':        'نوع الشكوى',
    'complaint_description': 'وصف الشكوى',
    'write_description':     'اكتب وصف الشكوى...',
    'description_required':  'يجب كتابة وصف الشكوى',
    'additional_notes':      'أي ملاحظات إضافية...',
    'notes_required':        'الملاحظات مطلوبة',
    'select_complaint_type': 'اختر نوع الشكوى',
    'complaint_required':    'يجب اختيار نوع الشكوى',
    'complaint_num_required':'رقم الشكوى مطلوب',
    'ban_vehicle':           'حظر المركبة',
    'vehicle_will_be_banned':'سيتم حظر المركبة عند الحفظ',
    'tap_to_ban':            'اضغط لحظر المركبة مع تسجيل المخالفة',
    'save_complaint':        'حفظ الشكوى',
    'complaint_saved':       'تم حفظ الشكوى',
    'complaint_and_banned':  'تم حفظ الشكوى وحظر المركبة',
    'complaint_recorded':    'تم تسجيل المخالفة',
    'fees_and_fine':         'الرسوم والغرامة',
    'allow_entry':           'السماح بالدخول',
    'extend_entry_date':     'تمديد تاريخ السماح بالدخول',
    'set_entry_date':        'تحديد تاريخ يُسمح فيه للمركبة بالدخول',
    'received':              'تم استلام',
    'amount_due':            'المبلغ المستحق:',
    'pending':               'معلق',
    'later':                 'لاحقاً',
    'save_and_close':        'حفظ وإغلاق',
    'select_entry_date':     'اختر تاريخ السماح بالدخول',
    'tap_to_select_date':    'اضغط لاختيار التاريخ...',
    'days':                  'يوم',
    'saved':                 'تم الحفظ',
    'fees_paid_entry_extended': 'تم حفظ المخالفة • رسوم مدفوعة • دخول مُمدَّد',
    'saved_fees_paid':       'تم حفظ المخالفة • رسوم مدفوعة',
    'saved_entry_extended':  'تم حفظ المخالفة • دخول مُمدَّد',
    'other_complaint':       'شكوى أخرى',
    // ── التقارير ──────────────────────────
    'daily_report':     'التقرير اليومي',
    'monthly_report':   'التقرير الشهري',
    'vehicle_report':   'تقرير المركبات',
    'violation_report': 'تقرير الشكاوى',
    'generate_report':  'إنشاء التقرير',
    'no_reports':       'لا توجد تقارير',
    // ── البوابات ──────────────────────────
    'gate_scanner':     'ماسح البوابة',
    'gate_entry':       'بوابة دخول',
    'gate_exit':        'بوابة خروج',
    'scan_rfid':        'امسح RFID',
    'floor':            'الطابق',
    'gate_number':      'رقم البوابة',
    'gate_type':        'نوع البوابة',
    'add_gate':         'إضافة بوابة',
    'no_gates':         'لا توجد بوابات',
    // ── الإعدادات ─────────────────────────
    'dark_mode':        'الوضع الليلي',
    'language':         'اللغة',
    'font_size':        'حجم الخط',
    'font_normal':      'عادي',
    'font_large':       'كبير',
    'font_xlarge':      'كبير جداً',
    'font_preview':     'معاينة: نظام إدارة المحطة',
    'account':          'الحساب',
    'security_section': 'الأمان',
    'data_mgmt':        'إدارة البيانات',
    'system':           'النظام',
    'notif_section':    'الإشعارات',
    'notif_enable':     'تفعيل الإشعارات',
    'notif_sound':      'صوت الإشعارات',
    'admin_email':      'إيميل الأدمن',
    'admin_email_hint': 'admin@example.com',
    'admin_email_note': 'إذا حُدِّد الإيميل يُشترط إدخاله عند تسجيل الدخول.\nاتركه فارغاً لإلغاء الاشتراط.',
    'email_saved':      'تم حفظ الإيميل',
    'email_removed':    'تم إزالة اشتراط الإيميل',
    'not_set':          'غير محدد',
    'clear_data':       'مسح جميع البيانات',
    'about_app':        'عن التطبيق',
    'app_version':      'الإصدار 1.0.0',
    'lang_ar':          'اللغة — عربي',
    'lang_en':          'اللغة — English',
    // ── عن التطبيق ────────────────────────
    'app_title':        'نظام إدارة المحطة',
    'app_subtitle':     'نظام إدارة طابور باستخدام تقنية RFID',
    'university':       'جامعة فلسطين التقنية — خضوري',
    'project_type':     'مشروع تخرج — هندسة الحاسوب',
    'technology':       'RFID — تحديد الهوية بالترددات الراديوية',
    'ok':               'حسناً',
    // ── تحذيرات وتأكيدات ──────────────────
    'danger_warning':        '⚠️ تحذير خطير',
    'will_delete':           'سيتم حذف:',
    'del_vehicles_lines':    'جميع المركبات والخطوط',
    'del_users':             'جميع المستخدمين',
    'del_events':            'جميع الأحداث والسجلات',
    'del_gates':             'جميع البوابات',
    'del_notifs':            'الإشعارات والتنبيهات',
    'del_profile':           'بيانات الحساب الشخصي',
    'irreversible':          '⚠️ هذا الإجراء لا يمكن التراجع عنه!',
    'delete_all':            'حذف كل شي',
    'delete_confirm':        'هل أنت متأكد؟',
    'delete_second_confirm': 'لا يمكن التراجع عن هذا الإجراء بعد تنفيذه.',
    'delete_ok':             'نعم، احذف',
    'data_deleted':          'تم حذف جميع البيانات بنجاح ✓',
    'logout_confirm':        'هل أنت متأكد أنك تريد تسجيل الخروج؟\nسيتم حفظ جميع البيانات.',
    // ── الأيام والأشهر ────────────────────
    'day_0': 'الأحد',    'day_1': 'الاثنين', 'day_2': 'الثلاثاء',
    'day_3': 'الأربعاء', 'day_4': 'الخميس',  'day_5': 'الجمعة',
    'day_6': 'السبت',
    'month_1':  'يناير',   'month_2':  'فبراير',  'month_3':  'مارس',
    'month_4':  'أبريل',   'month_5':  'مايو',    'month_6':  'يونيو',
    'month_7':  'يوليو',   'month_8':  'أغسطس',   'month_9':  'سبتمبر',
    'month_10': 'أكتوبر',  'month_11': 'نوفمبر',  'month_12': 'ديسمبر',
    // ── رسائل التحقق ──────────────────────
    'val_name_required':     'الاسم مطلوب',
    'val_name_short':        '3 أحرف على الأقل',
    'val_name_letters':      'أحرف فقط بدون أرقام أو رموز',
    'val_name_exists':       'الاسم مسجل مسبقاً',
    'val_username_required': 'اسم المستخدم مطلوب',
    'val_username_short':    '4 أحرف على الأقل',
    'val_username_spaces':   'لا مسافات',
    'val_pass_required':     'كلمة المرور مطلوبة',
    'val_pass_short':        '8 أحرف على الأقل',
    'val_pass_upper':        'يجب حرف كبير (A-Z)',
    'val_pass_number':       'يجب رقم (0-9)',
    'val_role_required':     'يجب اختيار الدور',
    'val_id_required':       'رقم الهوية مطلوب',
    'val_id_numbers':        'أرقام فقط',
    'val_id_length':         '9 أرقام بالضبط',
    'val_phone_required':    'رقم الهاتف مطلوب',
    'val_phone_length':      '10 أرقام بالضبط',
    'val_license_required':  'رقم الرخصة مطلوب',
    'val_grade_required':    'درجة الرخصة مطلوبة',
    'val_expiry_required':   'تاريخ انتهاء الرخصة مطلوب',
    'val_mac_invalid':       'صيغة غير صحيحة — مثال: AA:BB:CC:DD:EE:FF',
    'val_plate_required':    'رقم اللوحة مطلوب',
    'val_owner_required':    'اسم المالك مطلوب',
    'val_year_invalid':      'سنة غير صالحة',
    'val_date_required':     'التاريخ مطلوب',
    'val_date_format':       'الصيغة غير صحيحة — مثال: 2025-06-15',
    'val_date_invalid':      'تاريخ غير صالح',
    'val_date_future':       'يجب أن يكون في المستقبل',
    'val_date_past':         'يجب أن يكون في الماضي',
    'val_amount_required':   'المبلغ مطلوب',
    'val_amount_invalid':    'مبلغ غير صالح',
    'val_line_required':     'يجب اختيار الخط',
    'val_gate_required':     'يجب اختيار البوابة',
    'val_vehicle_required':  'يجب اختيار المركبة',
    'val_floor_required':    'رقم الطابق مطلوب',
    'val_gate_num_required': 'رقم البوابة مطلوب',
    // ── تغيير كلمة المرور ─────────────────
    'change_password':      'تغيير كلمة المرور',
    'new_password':         'كلمة المرور الجديدة',
    'confirm_password':     'تأكيد كلمة المرور',
    'passwords_not_match':  'كلمتا المرور غير متطابقتين',
    'password_changed':     'تم تغيير كلمة المرور ✓',
    // ── المخالفات ─────────────────────────
    'enter_violation_num':     'ادخل رقم المخالفة (مثال: A-201)',
    'enter_violation_name':    'ادخل اسم المخالفة',
    'violation_description':   'وصف المخالفة',
    'enter_violation_message': 'ادخل الرسالة',
    'violation_amount_shekel': 'مبلغ المخالفة (شيكل)',
    'enter_default_amount':    'ادخل القيمة الافتراضية (مثال: 120 شيكل)',
    'violation_value':         'قيمة المخالفة',
    'shekel':                  'شيكل',
    'violation_updated':       'تم تعديل المخالفة بنجاح',
    'save_violation':          'حفظ المخالفة',
    // ── ماسح البوابة ──────────────────────
    'select_gate':               'اختيار البوابة',
    'no_gates_added':            'لا توجد بوابات مضافة — اطلب من الأدمن إضافة بوابات من الإعدادات',
    'floor_number':              'رقم الطابق',
    'entrance':                  'مدخل',
    'selected_gate':             'البوابة المحددة:',
    'read_qr_rfid':              'قراءة QR / RFID',
    'enter_plate_or_rfid':       'أدخل رقم اللوحة أو RFID...',
    'scan_result':               'نتيجة الفحص',
    'vehicle_not_registered':    'مركبة غير مسجلة!',
    'no_vehicle_with_number':    'لا توجد مركبة بالرقم في النظام',
    'vehicle_banned':            'مركبة موقوفة!',
    'loading_expired':           'انتهت صلاحية التحميل!',
    'loading_date_not_set':      'تاريخ التحميل غير محدد',
    'expired_on':                'انتهى في:',
    'entry_allowed':             'دخول مسموح ✓',
    'exit_allowed':              'خروج مسموح ✓',
    'vehicle_details':           'تفاصيل المركبة والموقع',
    'vehicle_number_in_line':    'رقم المركبة في الخط',
    'owner':                     'المالك',
    'auto_violation':            'تم تسجيل مخالفة تلقائية في النظام',
    'ban_lifted':                'تم رفع الحظر ✓',
    'vehicle_banned_now':        'تم حظر المركبة ✗',
    'now_allowed':               'مسموح لها الآن',
    'not_allowed':               'ممنوعة من الدخول',
    'ban_lifted_for':            'تم رفع الحظر عن',
    'vehicle_banned_for':        'تم حظر المركبة',
    'add_new_gate':              'إضافة بوابة جديدة',
    'floor_example':             'مثال: 1',
    'gate_num_example':          'مثال: 1',
    'ip_example':                'مثال: 192.168.1.10',
    'gate_added':                'تمت إضافة',
    'edit_gate':                 'تعديل البوابة',
    'gate_updated':              'تم تحديث البوابة ✓',
    'delete_gate':               'حذف البوابة',
    'delete_gate_confirm':       'هل تريد حذف:',
    'gate_deleted':              'تم حذف البوابة',
    'select_gate_first':         'اختر بوابة أولاً',
    'manual_ban_unban':          'منع/رفع حظر مركبة',
    'search_vehicle':            'ابحث عن مركبة بالرقم أو المالك...',
    'no_results':                'لا توجد نتائج',
    'lift_ban':                  'رفع الحظر',
    'ban':                       'حظر',
    'search_to_ban':             'ابحث عن مركبة لمنعها أو رفع الحظر عنها',
    'attempt_entry_unregistered':'دخول مركبة غير مسجلة — رقم:',
    'attempt_entry_banned':      'محاولة دخول بمركبة موقوفة',
    'attempt_entry_expired':     'محاولة دخول بتاريخ تحميل منتهي',
    'loading_expired_notif':     'انتهاء صلاحية التحميل',
    'vehicle_tried_entry':       'المركبة حاولت الدخول وتاريخ تحميلها منتهي',
    'ban_vehicle_manually':      'حظر المركبة يدوياً',
    'lift_ban_vehicle':          'رفع الحظر عن المركبة',
    'not_specified':             'غير محدد',
    'banned_count':              'محظورة',
    'added_gates':               'البوابات المضافة',
    'gate_word':                 'بوابة',
    // ── الخطوط (جديد) ─────────────────────
    'add_line_new':          'إضافة خط جديد',
    'line_number':           'رقم الخط',
    'line_number_example':   'مثال: 101',
    'from':                  'من',
    'to':                    'إلى',
    'middle_stations':       'المحطات الوسطى',
    'line_supervisor':       'مشرف الخط',
    'no_supervisor_reg':     'لا يوجد مشرف مسجل',
    'fare_shekel':           'الأجرة (شيكل)',
    'loading_slots_count':   'عدد خانات التحميل',
    'add_line_btn':          'إضافة الخط',
    'no_entry_gates':        'لا توجد بوابات مدخل — أضف من الإعدادات',
    'no_exit_gates':         'لا توجد بوابات مخرج — أضف من الإعدادات',
    'choose_entry_gate':     'اختر بوابة الدخول',
    'choose_exit_gate':      'اختر بوابة الخروج',
    'edit_line_title':       'تعديل الخط',
    'delete_line':           'حذف الخط',
    'delete_line_confirm':   'هل أنت متأكد أنك تريد حذف',
    'delete_vehicle':        'حذف مركبة',
    'delete_vehicle_confirm':'هل تريد حذف المركبة رقم',
    'vehicle_added_success': 'تمت إضافة المركبة',
    'vehicle_added_suffix':  'بنجاح',
    'search_line':           'ابحث برقم الخط أو الاسم...',
    'filter_results':        'فلترة النتائج',
    'clear_all':             'مسح الكل',
    'no_supervisors':        'لا يوجد مشرفون',
    'route_label':           'المسار',
    'vehicle_count':         'عدد السيارات',
    'loading_slots_visual':  'خانات التحميل',
    'search_plate_owner':    'ابحث برقم اللوحة أو المالك...',
    'no_vehicles_found':     'لا توجد مركبات',
    'loading_not_set':       'التحميل: غير محدد',
    'expired_days_ago':      'انتهى منذ',
    'expires_today':         'ينتهي اليوم',
    'days_left':             'متبقي',
    'day_word':              'يوم',
    'loading_expiry_label':  'انتهاء التحميل',
    'edit_loading_date':     'تعديل تاريخ انتهاء التحميل',
    'slot_empty':            'فارغة',
    'total_vehicles':        'إجمالي المركبات',
    'ready_vehicles':        'جاهزة',
    'waiting_vehicles':      'في الانتظار',
    'violation_vehicles':    'مخالفة',
    'close_dialog':          'إغلاق',
    'lines_title':           'الخطوط',
    'route_full':            'المسار الكامل',
    'supervisor_label':      'مشرف',
    'choose_supervisor': 'اختر مشرفاً',
    'external_requests':     'الطلبات الخارجية',
    'new_badge':             'جديد',
    'request_type_parcel':   'طرد',
    'request_type_passengers':'ركاب',
    'req_status_pending':    'معلق',
    'req_status_accepted':   'مقبول',
    'req_status_in_progress':'قيد التنفيذ',
    'req_status_completed':  'مكتمل',
    'req_status_cancelled':  'مرفوض',
    'req_filter_accepted':   'مقبول',
    'req_filter_rejected':   'مرفوض',
    'no_requests':           'لا توجد طلبات',
    'passenger_count':       'راكب',
    'movement_order':        'أمر الحركة',
    'assigned_vehicle':      'المركبة',
    'assigned_driver':       'السائق',
    'assigned_line':         'الخط',
    'sender':                'المرسل',
    'location':              'الموقع',
    'destination':           'الوجهة',
    'supervisor_role': 'موظف أمن',
    'handled':        'تم التعامل معاها',
    'not_handled':    'لم يتم التعامل معاها',
  };

  static const Map<String, String> _en = {
    // ── Navigation ────────────────────────
    'dashboard':        'Dashboard',
    'gates':            'Gates',
    'lines':            'Lines',
    'users':            'Users',
    'vehicles':         'Vehicles',
    'violations':       'Complaints',
    'reports':          'Reports',
    'settings':         'Settings',
    'requests':         'Requests',
    'notifications':    'Notifications',
    'profile':          'Profile',
    'logout':           'Logout',
    // ── General Buttons ───────────────────
    'add':              'Add',
    'edit':             'Edit',
    'delete':           'Delete',
    'save':             'Save',
    'cancel':           'Cancel',
    'search':           'Search',
    'confirm':          'Confirm',
    'close':            'Close',
    'yes':              'Yes',
    'no':               'No',
    'back':             'Back',
    'next':             'Next',
    'filter':           'Filter',
    'all':              'All',
    'loading':          'Loading...',
    'no_data':          'No data available',
    'coming_soon':      'Coming soon...',
    'choose':           'Choose',
    'choose_role':      'Select role',
    'choose_line':      'Select line',
    'choose_gate':      'Select gate',
    'choose_driver':    'Select driver',
    'choose_supervisor':'Choose supervisor',
    'name':             'Name',
    'date':             'Date',
    'note':             'Note',
    'notes':            'Notes',
    'amount':           'Amount',
    'status':           'Status',
    'actions':          'Actions',
    'details':          'Details',
    'info':             'Info',
    'required':         'Required',
    'optional':         'Optional',
    'active':           'Active',
    'inactive':         'Inactive',
    'suspended':        'Suspended',
    'unknown':          'Unknown',
    'preview':          'Preview',
    'print':            'Print',
    'export':           'Export',
    'share':            'Share',
    'copy':             'Copy',
    'copied':           'Copied',
    'error':            'Error',
    'success':          'Success',
    'warning':          'Warning',
    // ── Dashboard ─────────────────────────
    'greeting_morning': 'Good morning',
    'greeting_afternoon':'Good afternoon',
    'greeting_evening': 'Good evening',
    'station_name':     'Central Bus Station — Hebron',
    'vehicle':          'Vehicle',
    'line':             'Line',
    'user':             'User',
    'complaint':        'Complaint',
    'in_line':          'In Line',
    'banned':           'Banned',
    'ready':            'Ready',
    'waiting':          'Waiting',
    'vehicle_status':   'Vehicle Status',
    'event_stats':      'Event Statistics',
    'no_vehicles':      'No vehicles yet',
    'no_events':        'No events yet',
    'entry':            'Entry',
    'exit':             'Exit',
    'violation':        'Violation',
    // ── Users ─────────────────────────────
    'add_user':         'Add User',
    'edit_user':        'Edit User',
    'user_info':        'User Info',
    'full_name':        'Full Name',
    'username':         'Username',
    'password':         'Password',
    'role':             'Role',
    'id_number':        'ID Number',
    'phone':            'Phone Number',
    'phone_optional':   'Phone 2 (optional)',
    'phone_required':   'Phone (required)',
    'license_num':      'License Number',
    'license_grade':    'License Grade',
    'license_expiry':   'Driver License Expiry',
    'medical_expiry':   'Medical Exam Expiry',
    'mac_address':      'MAC Address',
    'account_active':   'Account Active',
    'save_user':        'Save User',
    'driver':           'Driver',
    'security':         'Security Officer',
    'supervisor':       'Line Supervisor',
    'license_data':     'License & Medical Data',
    'user_saved':       'User saved successfully ✓',
    'enter_name':       'Enter full name',
    'enter_username':   'Enter username',
    'enter_password':   'Enter password',
    'enter_id':         'ID number (9 digits)',
    'enter_phone':      '05xxxxxxxx',
    'enter_license':    'Enter license number',
    'enter_grade':      'Example: B, C, D',
    'enter_mac':        'Example: AA:BB:CC:DD:EE:FF',
    'date_format':      'YYYY-MM-DD',
    'license_issue':    'License issue date',
    // ── Vehicles ──────────────────────────
    'add_vehicle':      'Add Vehicle',
    'edit_vehicle':     'Edit Vehicle',
    'vehicle_info':     'Vehicle Info',
    'plate_number':     'Plate Number',
    'manufacturer':     'Manufacturer',
    'model':            'Model',
    'year':             'Year',
    'chassis':          'Chassis Number',
    'op_lic_num':       'Operating License Number',
    'op_lic_exp':       'Operating License Expiry',
    'lic_exp':          'License Expiry',
    'insurance_exp':    'Insurance Expiry',
    'loading_exp':      'Loading Expiry',
    'owner_name':       'Owner Name',
    'owner_phone':      'Owner Phone',
    'owner_id':         'Owner ID',
    'status_banned':    'Banned',
    'status_waiting':   'Waiting',
    'status_ready':     'Ready',
    'status_in_line':   'In Line',
    'vehicle_saved':    'Vehicle saved successfully ✓',
    'rfid_tag':         'RFID Number',
    'enter_plate':      'Enter plate number',
    'enter_chassis':    'Enter chassis number',
    'enter_maker':      'Example: Toyota',
    'enter_model':      'Example: Hiace',
    'enter_year':       'Example: 2020',
    'enter_rfid':       'Enter RFID number',
    'enter_owner':      'Enter owner name',
    'enter_owner_phone':'Enter owner phone',
    'enter_owner_id':   'Enter owner ID',
    'operating_license':'Operating License',
    'enter_op_lic':     'Example: OP-2024-556',
    'owner_info':       'Owner Information',
    'driver_and_line':  'Driver & Line',
    'driver_required':  'Driver is required',
    'save_changes':     'Save Changes',
    // ── Lines ─────────────────────────────
    'add_line':         'Add Line',
    'edit_line':        'Edit Line',
    'line_info':        'Line Info',
    'line_name':        'Line Name',
    'line_route':       'Route',
    'entry_gate':       'Entry Gate',
    'exit_gate':        'Exit Gate',
    'fare':             'Fare',
    'loading_slots':    'Loading Slots',
    'no_lines':         'No lines yet',
    'no_supervisor':    'No supervisor',
    'no_driver':        'No driver',
    // ── Violations ────────────────────────
    'add_violation':    'Add Complaint',
    'edit_violation':   'Edit Complaint',
    'violation_type':   'Complaint Type',
    'violation_amount': 'Fine Amount',
    'fees_paid':        'Fine paid',
    'fees_unpaid':      'Fine not paid',
    'no_violations':    'No complaints yet',
    'complaint_number':      'Complaint Number',
    'complaint_type':        'Complaint Type',
    'complaint_description': 'Complaint Description',
    'write_description':     'Write complaint description...',
    'description_required':  'Description is required',
    'additional_notes':      'Any additional notes...',
    'notes_required':        'Notes are required',
    'select_complaint_type': 'Select complaint type',
    'complaint_required':    'Complaint type is required',
    'complaint_num_required':'Complaint number is required',
    'ban_vehicle':           'Ban Vehicle',
    'vehicle_will_be_banned':'Vehicle will be banned on save',
    'tap_to_ban':            'Tap to ban vehicle with complaint',
    'save_complaint':        'Save Complaint',
    'complaint_saved':       'Complaint saved',
    'complaint_and_banned':  'Complaint saved & vehicle banned',
    'complaint_recorded':    'Complaint Recorded',
    'fees_and_fine':         'Fees & Fine',
    'allow_entry':           'Allow Entry',
    'extend_entry_date':     'Extend entry date',
    'set_entry_date':        'Set a date the vehicle is allowed to enter',
    'received':              'Received',
    'amount_due':            'Amount due:',
    'pending':               'Pending',
    'later':                 'Later',
    'save_and_close':        'Save & Close',
    'select_entry_date':     'Select entry date',
    'tap_to_select_date':    'Tap to select date...',
    'days':                  'days',
    'saved':                 'Saved',
    'fees_paid_entry_extended': 'Saved • Fees paid • Entry extended',
    'saved_fees_paid':       'Saved • Fees paid',
    'saved_entry_extended':  'Saved • Entry extended',
    'other_complaint':       'Other complaint',
    // ── Reports ───────────────────────────
    'daily_report':     'Daily Report',
    'monthly_report':   'Monthly Report',
    'vehicle_report':   'Vehicle Report',
    'violation_report': 'Complaints Report',
    'generate_report':  'Generate Report',
    'no_reports':       'No reports yet',
    // ── Gates ─────────────────────────────
    'gate_scanner':     'Gate Scanner',
    'gate_entry':       'Entry Gate',
    'gate_exit':        'Exit Gate',
    'scan_rfid':        'Scan RFID',
    'floor':            'Floor',
    'gate_number':      'Gate Number',
    'gate_type':        'Gate Type',
    'add_gate':         'Add Gate',
    'no_gates':         'No gates yet',
    // ── Settings ──────────────────────────
    'dark_mode':        'Dark Mode',
    'language':         'Language',
    'font_size':        'Font Size',
    'font_normal':      'Normal',
    'font_large':       'Large',
    'font_xlarge':      'Extra Large',
    'font_preview':     'Preview: Station Management System',
    'account':          'Account',
    'security_section': 'Security',
    'data_mgmt':        'Data Management',
    'system':           'System',
    'notif_section':    'Notifications',
    'notif_enable':     'Enable Notifications',
    'notif_sound':      'Notification Sound',
    'admin_email':      'Admin Email',
    'admin_email_hint': 'admin@example.com',
    'admin_email_note': 'If set, this email is required at login.\nLeave empty to disable.',
    'email_saved':      'Email saved',
    'email_removed':    'Email requirement removed',
    'not_set':          'Not set',
    'clear_data':       'Clear All Data',
    'about_app':        'About',
    'app_version':      'Version 1.0.0',
    'lang_ar':          'Language — Arabic',
    'lang_en':          'Language — English',
    // ── About ─────────────────────────────
    'app_title':        'Station Management System',
    'app_subtitle':     'Queue management system using RFID technology',
    'university':       'Palestine Technical University — Kadoorie',
    'project_type':     'Graduation Project — Computer Engineering',
    'technology':       'RFID — Radio Frequency Identification',
    'ok':               'OK',
    // ── Warnings & Confirms ───────────────
    'danger_warning':        '⚠️ Danger Warning',
    'will_delete':           'This will delete:',
    'del_vehicles_lines':    'All vehicles and lines',
    'del_users':             'All users',
    'del_events':            'All events and logs',
    'del_gates':             'All gates',
    'del_notifs':            'Notifications and alerts',
    'del_profile':           'Profile data',
    'irreversible':          '⚠️ This action cannot be undone!',
    'delete_all':            'Delete Everything',
    'delete_confirm':        'Are you sure?',
    'delete_second_confirm': 'This action cannot be undone once executed.',
    'delete_ok':             'Yes, delete',
    'data_deleted':          'All data deleted successfully ✓',
    'logout_confirm':        'Are you sure you want to logout?\nAll data will be saved.',
    // ── Days & Months ─────────────────────
    'day_0': 'Sunday',    'day_1': 'Monday',    'day_2': 'Tuesday',
    'day_3': 'Wednesday', 'day_4': 'Thursday',  'day_5': 'Friday',
    'day_6': 'Saturday',
    'month_1':  'January',   'month_2':  'February', 'month_3':  'March',
    'month_4':  'April',     'month_5':  'May',      'month_6':  'June',
    'month_7':  'July',      'month_8':  'August',   'month_9':  'September',
    'month_10': 'October',   'month_11': 'November', 'month_12': 'December',
    // ── Validation Messages ───────────────
    'val_name_required':     'Name is required',
    'val_name_short':        'At least 3 characters',
    'val_name_letters':      'Letters only, no numbers or symbols',
    'val_name_exists':       'Name already exists',
    'val_username_required': 'Username is required',
    'val_username_short':    'At least 4 characters',
    'val_username_spaces':   'No spaces allowed',
    'val_pass_required':     'Password is required',
    'val_pass_short':        'At least 8 characters',
    'val_pass_upper':        'Must contain uppercase letter',
    'val_pass_number':       'Must contain a number',
    'val_role_required':     'Role is required',
    'val_id_required':       'ID is required',
    'val_id_numbers':        'Numbers only',
    'val_id_length':         'Exactly 9 digits',
    'val_phone_required':    'Phone is required',
    'val_phone_length':      'Exactly 10 digits',
    'val_license_required':  'License number is required',
    'val_grade_required':    'License grade is required',
    'val_expiry_required':   'License expiry is required',
    'val_mac_invalid':       'Invalid format — Example: AA:BB:CC:DD:EE:FF',
    'val_plate_required':    'Plate number is required',
    'val_owner_required':    'Owner name is required',
    'val_year_invalid':      'Invalid year',
    'val_date_required':     'Date is required',
    'val_date_format':       'Invalid format — Example: 2025-06-15',
    'val_date_invalid':      'Invalid date',
    'val_date_future':       'Must be in the future',
    'val_date_past':         'Must be in the past',
    'val_amount_required':   'Amount is required',
    'val_amount_invalid':    'Invalid amount',
    'val_line_required':     'Line is required',
    'val_gate_required':     'Gate is required',
    'val_vehicle_required':  'Vehicle is required',
    'val_floor_required':    'Floor number is required',
    'val_gate_num_required': 'Gate number is required',
    // ── Password Change ───────────────────
    'change_password':      'Change Password',
    'new_password':         'New Password',
    'confirm_password':     'Confirm Password',
    'passwords_not_match':  'Passwords do not match',
    'password_changed':     'Password changed successfully ✓',
    // ── Violations ────────────────────────
    'enter_violation_num':     'Enter violation number (e.g., A-201)',
    'enter_violation_name':    'Enter violation name',
    'violation_description':   'Violation Description',
    'enter_violation_message': 'Enter message',
    'violation_amount_shekel': 'Violation Amount (Shekel)',
    'enter_default_amount':    'Enter default value (e.g., 120 shekel)',
    'violation_value':         'Violation value',
    'shekel':                  'shekel',
    'violation_updated':       'Violation updated successfully',
    'save_violation':          'Save Violation',
    // ── Gate Scanner ──────────────────────
    'select_gate':               'Select Gate',
    'no_gates_added':            'No gates added — ask admin to add gates from settings',
    'floor_number':              'Floor Number',
    'entrance':                  'Entrance',
    'selected_gate':             'Selected Gate:',
    'read_qr_rfid':              'Read QR / RFID',
    'enter_plate_or_rfid':       'Enter plate number or RFID...',
    'scan_result':               'Scan Result',
    'vehicle_not_registered':    'Vehicle Not Registered!',
    'no_vehicle_with_number':    'No vehicle with number in system',
    'vehicle_banned':            'Vehicle Banned!',
    'loading_expired':           'Loading Expired!',
    'loading_date_not_set':      'Loading date not set',
    'expired_on':                'Expired on:',
    'entry_allowed':             'Entry Allowed ✓',
    'exit_allowed':              'Exit Allowed ✓',
    'vehicle_details':           'Vehicle & Location Details',
    'vehicle_number_in_line':    'Vehicle Number in Line',
    'owner':                     'Owner',
    'auto_violation':            'Auto violation recorded in system',
    'ban_lifted':                'Ban Lifted ✓',
    'vehicle_banned_now':        'Vehicle Banned ✗',
    'now_allowed':               'Now allowed',
    'not_allowed':               'Not allowed to enter',
    'ban_lifted_for':            'Ban lifted for',
    'vehicle_banned_for':        'Vehicle banned',
    'add_new_gate':              'Add New Gate',
    'floor_example':             'Example: 1',
    'gate_num_example':          'Example: 1',
    'ip_example':                'Example: 192.168.1.10',
    'gate_added':                'Gate added',
    'edit_gate':                 'Edit Gate',
    'gate_updated':              'Gate updated ✓',
    'delete_gate':               'Delete Gate',
    'delete_gate_confirm':       'Delete:',
    'gate_deleted':              'Gate deleted',
    'select_gate_first':         'Select gate first',
    'manual_ban_unban':          'Ban/Unban Vehicle',
    'search_vehicle':            'Search by plate or owner...',
    'no_results':                'No results',
    'lift_ban':                  'Lift Ban',
    'ban':                       'Ban',
    'search_to_ban':             'Search to ban or unban a vehicle',
    'attempt_entry_unregistered':'Unregistered vehicle entry — number:',
    'attempt_entry_banned':      'Attempt entry with banned vehicle',
    'attempt_entry_expired':     'Attempt entry with expired loading',
    'loading_expired_notif':     'Loading Expired',
    'vehicle_tried_entry':       'Vehicle tried entry with expired loading',
    'ban_vehicle_manually':      'Ban vehicle manually',
    'lift_ban_vehicle':          'Lift vehicle ban',
    'not_specified':             'Not specified',
    'banned_count':              'banned',
    'added_gates':               'Added Gates',
    'gate_word':                 'Gate',
    // ── Lines (new) ───────────────────────
    'add_line_new':          'Add New Line',
    'line_number':           'Line Number',
    'line_number_example':   'Example: 101',
    'from':                  'From',
    'to':                    'To',
    'middle_stations':       'Middle Stations',
    'line_supervisor':       'Line Supervisor',
    'no_supervisor_reg':     'No supervisor registered',
    'fare_shekel':           'Fare (Shekel)',
    'loading_slots_count':   'Loading Slots',
    'add_line_btn':          'Add Line',
    'no_entry_gates':        'No entry gates — add from settings',
    'no_exit_gates':         'No exit gates — add from settings',
    'choose_entry_gate':     'Select entry gate',
    'choose_exit_gate':      'Select exit gate',
    'edit_line_title':       'Edit Line',
    'delete_line':           'Delete Line',
    'delete_line_confirm':   'Are you sure you want to delete',
    'delete_vehicle':        'Delete Vehicle',
    'delete_vehicle_confirm':'Delete vehicle number',
    'vehicle_added_success': 'Vehicle',
    'vehicle_added_suffix':  'added successfully',
    'search_line':           'Search by line number or name...',
    'filter_results':        'Filter Results',
    'clear_all':             'Clear All',
    'no_supervisors':        'No supervisors found',
    'route_label':           'Route',
    'vehicle_count':         'Vehicles',
    'loading_slots_visual':  'Loading Slots',
    'search_plate_owner':    'Search by plate or owner...',
    'no_vehicles_found':     'No vehicles',
    'loading_not_set':       'Loading: not set',
    'expired_days_ago':      'Expired',
    'expires_today':         'Expires today',
    'days_left':             'Left',
    'day_word':              'days',
    'loading_expiry_label':  'Loading Expiry',
    'edit_loading_date':     'Edit Loading Expiry Date',
    'slot_empty':            'Empty',
    'total_vehicles':        'Total Vehicles',
    'ready_vehicles':        'Ready',
    'waiting_vehicles':      'Waiting',
    'violation_vehicles':    'Violation',
    'close_dialog':          'Close',
    'lines_title':           'Lines',
    'route_full':            'Full Route',
    'supervisor_label':      'Supervisor',
    'external_requests':     'External Requests',
    'new_badge':             'new',
    'request_type_parcel':   'Parcel',
    'request_type_passengers':'Passengers',
    'req_status_pending':    'Pending',
    'req_status_accepted':   'Accepted',
    'req_status_in_progress':'In Progress',
    'req_status_completed':  'Completed',
    'req_status_cancelled':  'Rejected',
    'req_filter_accepted':   'Accepted',
    'req_filter_rejected':   'Rejected',
    'no_requests':           'No requests',
    'passenger_count':       'passenger',
    'movement_order':        'Movement Order',
    'assigned_vehicle':      'Vehicle',
    'assigned_driver':       'Driver',
    'assigned_line':         'Line',
    'sender':                'Sender',
    'location':              'Location',
    'destination':           'Destination',
    'supervisor_role': 'Security Officer',
    'handled':        'Handled',
    'not_handled':    'Not Handled',
  };

  static void toggleLanguage() {
    langNotifier.value = langNotifier.value == 'ar' ? 'en' : 'ar';
  }

  static bool get isArabic => langNotifier.value == 'ar';
  static bool get isEnglish => langNotifier.value == 'en';
}



